### ISSUE TITLE
Build from source README

### ISSUE THREAD

**Issue by D3vil0p3r** [nzymedefense/nzyme#1042]
### Feature/Change Description and Goal

Among the source files I don't see any document explaining how to build from source. I run:
```
mvn package -DskipTests=true
```
and it builds with success. Then, it is not clear which file must be executed to run nzyme. I tried to run:
```
java -jar target/nzyme-2.0.0-alpha.14-SNAPSHOT.jar
```
but I get the following error:
```
Exception in thread "main" com.beust.jcommander.ParameterException: The following option is required: [--config-file | -c]
	at com.beust.jcommander.JCommander.validateOptions(JCommander.java:388)
	at com.beust.jcommander.JCommander.parse(JCommander.java:357)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at app.nzyme.core.Main.main(Main.java:51)
```
Could you please create a documentation about building from source?

**Comment by lennartkoopmann** [comment]
Hi! We'll add this to the documentation soon-ish.

You seem to have successfully compiled the program, but are not passing the `-c nzyme.conf` parameter when you are executing it.
