### ISSUE TITLE
nzyme-tracker TEXTGUI blank display

### ISSUE THREAD

**Issue by shandshellin** [nzymedefense/nzyme#809]
[groundstation-listener-0] WARN  horse.wtf.nzyme.bandits.trackers.devices.SX126XLoRaHat - Error in read loop.
java.security.GeneralSecurityException: ciphertext too short
        at com.google.crypto.tink.subtle.AesGcmJce.decrypt(AesGcmJce.java:101) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.security.transport.TransportEncryption.decrypt(TransportEncryption.java:50) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.bandits.trackers.devices.SX126XLoRaHat.readLoop(SX126XLoRaHat.java:145) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
03:10:35.724 [textguihid-0] ERROR horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID - Could not initialize Text GUI HID.
java.io.IOException: Cannot run program "/bin/stty": /dev/tty (No such device or address)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[?:?]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[?:?]
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.exec(UnixLikeTTYTerminal.java:158) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.runSTTYCommand(UnixLikeTTYTerminal.java:150) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.saveTerminalSettings(UnixLikeTTYTerminal.java:113) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTerminal.acquire(UnixLikeTerminal.java:86) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.realAcquire(UnixLikeTTYTerminal.java:86) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.<init>(UnixLikeTTYTerminal.java:77) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.ansi.UnixTerminal.<init>(UnixTerminal.java:90) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.ansi.UnixTerminal.<init>(UnixTerminal.java:80) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createUnixTerminal(DefaultTerminalFactory.java:478) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createHeadlessTerminal(DefaultTerminalFactory.java:143) ~[nzyme-1.2.2.jar:?]
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createTerminal(DefaultTerminalFactory.java:113) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID.initializeGUI(TextGUIHID.java:232) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID.lambda$initialize$0(TextGUIHID.java:99) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.FileNotFoundException: /dev/tty (No such device or address)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at java.lang.ProcessImpl.start(ProcessImpl.java:235) ~[?:?]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) ~[?:?]
        ... 19 more
03:10:35.918 [textguihid-0] ERROR horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID - Could not initialize Text GUI HID.
java.lang.IllegalArgumentException: selectedRow must be >= 0 but was -1
        at com.googlecode.lanterna.gui2.table.Table.setSelectedRow(Table.java:315) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID.initializeGUI(TextGUIHID.java:266) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID.lambda$initialize$0(TextGUIHID.java:99) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
03:11:00.804 [channel-designator-0] INFO  horse.wtf.nzyme.bandits.trackers.trackerlogic.ChannelDesignator - No contacts during cycle. Resuming operations on configured probe channels.
03:11:00.810 [channel-designator-0] INFO  horse.wtf.nzyme.bandits.trackers.trackerlogic.ChannelDesignator - No contacts during cycle. Resuming operations on configured probe channels.
03:11:30.804 [channel-designator-0] INFO  horse.wtf.nzyme.bandits.trackers.trackerlogic.ChannelDesignator - No contacts during cycle. Resuming operations on configured probe channels.
03:11:30.810 [channel-designator-0] INFO  horse.wtf.nzyme.bandits.trackers.trackerlogic.ChannelDesignator - No contacts during cycle. Resuming operations on configured probe channels.
03:11:39.317 [groundstation-listener-0] WARN  horse.wtf.nzyme.bandits.trackers.devices.SX126XLoRaHat - Error in read loop.
java.security.GeneralSecurityException: ciphertext too short
        at com.google.crypto.tink.subtle.AesGcmJce.decrypt(AesGcmJce.java:101) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.security.transport.TransportEncryption.decrypt(TransportEncryption.java:50) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.bandits.trackers.devices.SX126XLoRaHat.readLoop(SX126XLoRaHat.java:145) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

Tracker is online and talking to the leader but i cannot get the TEXTGUI to work. Running on Buster. Config is basic so not sur ewhat the problem is.

**Comment by shandshellin** [comment]
This is the real snag

15:52:10.827 [textguihid-0] ERROR horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID - Could not initialize Text GUI HID.
java.lang.IllegalArgumentException: selectedRow must be >= 0 but was -1
        at com.googlecode.lanterna.gui2.table.Table.setSelectedRow(Table.java:315) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID.initializeGUI(TextGUIHID.java:266) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID.lambda$initialize$0(TextGUIHID.java:99) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by shandshellin** [comment]
does this only work with a specific display, i havea 4 inch touch screen and all i get is a blank with a cursor. Webgui works fine, nzyme itself is good as well. Any help?

**Comment by lennartkoopmann** [comment]
It should work with any display. What is the full log of nzyme?

**Comment by shandshellin** [comment]
The first post has the output of the log, it just loops that output when the textguid option is enabled. Screen has a blank cursor, screen works fine otherwise during boot and to see the cli. Webgui works fine also. Saw some java errors in there. Is there some other log?

**Comment by shandshellin** [comment]
03:10:35.918 [textguihid-0] ERROR horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID - Could not initialize Text GUI HID.
java.lang.IllegalArgumentException: selectedRow must be >= 0 but was -1
at com.googlecode.lanterna.gui2.table.Table.setSelectedRow(Table.java:315) ~[nzyme-1.2.2.jar:?]
at horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID.initializeGUI(TextGUIHID.java:266) ~[nzyme-1.2.2.jar:?]
at horse.wtf.nzyme.bandits.trackers.hid.TextGUIHID.lambda$initialize$0(TextGUIHID.java:99) ~[nzyme-1.2.2.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]

This seems to be the snag.

**Comment by shandshellin** [comment]
The screen is set to mirror hdmi output.

**Comment by shandshellin** [comment]
using this touchscreen 
https://www.waveshare.com/wiki/3.5inch_RPi_LCD_(A)
